name: Hotfix

on:
  push:
    branches: [ hotfix/** ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [ Debug ]

    runs-on: windows-latest

    env:
      Solution_Name: SpiraToDevOps.sln
      Project_Path: SpiraToDevOps\SpiraToDevOps.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0