# Main
#
# Build project (Release)
# Sign project
# Deploy project (Release)
#
# Unit-test
#
# Build installers
# Sign installers
# Deploy (Release)

name: Main

on:
  push:
    branches: [ main ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [ Debug, Release ]

    runs-on: windows-latest

    env:
      Solution_Name: SpiraToDevOps.sln
      Project_Path: SpiraToDevOps\SpiraToDevOps.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
