# Release PullRequest
#
# From 
# Dev 
# to 
# Release

name: ReleasePR

on: 
  pull_request:
    branches: [ release ]
 
jobs: 
  build: 
    strategy: 
      matrix: 
        configuration: [ Debug, Release ] 
 
    runs-on: windows-latest 
 
    env: 
      Solution_Name: SpiraToDevOps.sln 
      Project_Path: SpiraToDevOps\SpiraToDevOps.csproj 
 
    steps: 
    - name: Checkout 
      uses: actions/checkout@v2 
      with: 
        fetch-depth: 0